name: Workflow checks

on:
  pull_request:
  push:
    branches: [main]
    paths: [".github/workflows/**"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    permissions:
      contents: read
    uses: bolens/.github/.github/workflows/reusable-actionlint.yml@dca68e2aef0df5caae0e6d03470decd17c7ae1e0
    with:
      security-audit: true
